//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Language {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExcelAddIn.Properties.Language", typeof(Language).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Action Var.
        /// </summary>
        internal static string AddActionVar_label {
            get {
                return ResourceManager.GetString("AddActionVar_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Check Var.
        /// </summary>
        internal static string AddCheckVar_label {
            get {
                return ResourceManager.GetString("AddCheckVar_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Step.
        /// </summary>
        internal static string AddStep_label {
            get {
                return ResourceManager.GetString("AddStep_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auto Update.
        /// </summary>
        internal static string AutoUpdate_CB_label {
            get {
                return ResourceManager.GetString("AutoUpdate_CB_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Test.
        /// </summary>
        internal static string CheckTest_label {
            get {
                return ResourceManager.GetString("CheckTest_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, unselect the cell you are editing. This may cause unexecepted behaviours..
        /// </summary>
        internal static string Error_Excel_User_Editing {
            get {
                return ResourceManager.GetString("Error_Excel_User_Editing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Excel application has been detected.
        ///Please, open a PR Excel file to use the TCMS Validation Tool Manager..
        /// </summary>
        internal static string Exception_ExcelApplication_Missing {
            get {
                return ResourceManager.GetString("Exception_ExcelApplication_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A functionality is already running on this workbook.
        ///Please, wait it finished before trying to use an other function..
        /// </summary>
        internal static string Exception_ExcelApplication_NotAvailable {
            get {
                return ResourceManager.GetString("Exception_ExcelApplication_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This function has not been implemented yet for this version..
        /// </summary>
        internal static string Exception_NotImplemented {
            get {
                return ResourceManager.GetString("Exception_NotImplemented", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update date: {0}.
        /// </summary>
        internal static string macro_update_date_label {
            get {
                return ResourceManager.GetString("macro_update_date_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version: {0}.
        /// </summary>
        internal static string macro_version_label {
            get {
                return ResourceManager.GetString("macro_version_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New PR.
        /// </summary>
        internal static string NewPR_label {
            get {
                return ResourceManager.GetString("NewPR_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Published.
        /// </summary>
        internal static string NotPublished {
            get {
                return ResourceManager.GetString("NotPublished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plan to Tests.
        /// </summary>
        internal static string PlanToTests_label {
            get {
                return ResourceManager.GetString("PlanToTests_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Action Var.
        /// </summary>
        internal static string RemoveActionVar_label {
            get {
                return ResourceManager.GetString("RemoveActionVar_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Check Var.
        /// </summary>
        internal static string RemoveCheckVar_label {
            get {
                return ResourceManager.GetString("RemoveCheckVar_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Step.
        /// </summary>
        internal static string RemoveStep_label {
            get {
                return ResourceManager.GetString("RemoveStep_label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To TestStand.
        /// </summary>
        internal static string ToTestStand {
            get {
                return ResourceManager.GetString("ToTestStand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning !.
        /// </summary>
        internal static string Warning_title {
            get {
                return ResourceManager.GetString("Warning_title", resourceCulture);
            }
        }
    }
}
